version: "3.1"

services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - recognizer
  recognizer:
    build: ./recognizer/
    expose:
      - "80"
    volumes:
      - ./recognizer:/recognizer
      - ./images:/images
    working_dir: /recognizer
    command: /bin/sh -c "python face_recognizer.py"